import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import type { Command } from "commander";
import { assertInitialized } from "../utils/config.ts";

const PRIME_COMMAND = "sd prime 2>/dev/null || true";

// Old versions injected this block into CLAUDE.md; onboard strips it.
const LEGACY_BLOCK = /\n*<!-- seeds:start -->[\s\S]*?<!-- seeds:end -->\n*/;

const SEEDS_SKILL = `---
name: seeds
description: How to use Seeds (sd), this project's git-native task tracker — find, create, plan, update and close tickets. Use whenever you read or change Seeds tickets or run sd commands.
---

<!-- Generated by sd onboard. Re-run it to update; local edits are overwritten. -->

# Seeds

Tickets live in \`.seeds/\` and are committed with the code. \`sd prime\` runs at session start and shows current work.

## Find work

\`\`\`bash
sd ready          # unblocked, plan submitted if required
sd list           # all open tickets
sd show <id>      # full ticket, including its module scope
\`\`\`

## Create tickets

\`\`\`bash
sd create --type epic --title "Feature name"
sd create --type task --title "..." --parent <epic> \\
  --module <name> --entry <path> --must-not-touch <a,b>
sd dep add <ticket> <blocker>
\`\`\`

The module scope is set **only when the ticket is created**: which module the work belongs to, its entry point, and what it must not touch. The module flags are optional. Leave them off when the scope isn't clear yet, and never make up a scope.

Epic plans can give a step a \`"module"\`, and the task spawned from that step inherits it.

## Work a ticket

\`\`\`bash
sd update <id> --status in_progress
sd plan prompt <id>                      # plan template, if the ticket requires one
sd plan submit <id> --plan plan.json
sd update <id> --status review           # done, awaiting review
sd close <id> --reason "..."
sd sync                                  # validate, stage, commit .seeds/
\`\`\`

Stay inside the ticket's module. If the work needs to touch something on its \`must not touch\` list, stop and ask.
`;

export function registerOnboardCommand(program: Command): void {
	program
		.command("onboard")
		.description("Add the Seeds skill and SessionStart hook for Claude Code")
		.action(() => {
			assertInitialized();
			const cwd = process.cwd();

			// 1. Skill file — loaded by the agent on demand, not every session
			const skillDir = join(cwd, ".claude", "skills", "seeds");
			const skillPath = join(skillDir, "SKILL.md");
			if (existsSync(skillPath) && readFileSync(skillPath, "utf-8") === SEEDS_SKILL) {
				console.log(chalk.dim("  Seeds skill already up to date"));
			} else {
				mkdirSync(skillDir, { recursive: true });
				writeFileSync(skillPath, SEEDS_SKILL, "utf-8");
				console.log(chalk.green("✓ Seeds skill written to .claude/skills/seeds/SKILL.md"));
			}

			// 2. SessionStart hook in .claude/settings.json
			const settingsPath = join(cwd, ".claude", "settings.json");
			const settings = existsSync(settingsPath)
				? (JSON.parse(readFileSync(settingsPath, "utf-8")) as Record<string, unknown>)
				: {};
			const hooks = (settings.hooks ?? {}) as Record<string, unknown>;
			const sessionStart = (hooks.SessionStart ?? []) as Array<{
				matcher: string;
				hooks: Array<{ type: string; command: string }>;
			}>;
			const present = sessionStart.some((entry) =>
				entry.hooks?.some((h) => h.command?.includes("sd prime")),
			);
			if (present) {
				console.log(chalk.dim("  SessionStart hook already present"));
			} else {
				sessionStart.push({ matcher: "", hooks: [{ type: "command", command: PRIME_COMMAND }] });
				hooks.SessionStart = sessionStart;
				settings.hooks = hooks;
				writeFileSync(settingsPath, `${JSON.stringify(settings, null, "\t")}\n`, "utf-8");
				console.log(chalk.green("✓ SessionStart hook added to .claude/settings.json"));
			}

			// 3. Remove the block older versions put in CLAUDE.md
			const claudeMdPath = join(cwd, "CLAUDE.md");
			if (existsSync(claudeMdPath)) {
				const content = readFileSync(claudeMdPath, "utf-8");
				if (LEGACY_BLOCK.test(content)) {
					const cleaned = content.replace(LEGACY_BLOCK, "\n\n").trim();
					writeFileSync(claudeMdPath, cleaned ? `${cleaned}\n` : "", "utf-8");
					console.log(chalk.green("✓ Removed old Seeds block from CLAUDE.md"));
				}
			}
		});
}
