import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import type { Command } from "commander";
import { assertInitialized } from "../utils/config.ts";

const PRIME_COMMAND = "sd prime 2>/dev/null || true";

// Old versions injected this block into CLAUDE.md; onboard strips it.
const LEGACY_BLOCK = /\n*<!-- seeds:start -->[\s\S]*?<!-- seeds:end -->\n*/;

const SEEDS_SKILL = `---
name: seeds
description: How to use Seeds (sd), this project's git-native task tracker — find, create, plan, update and close tickets. Use whenever you read or change Seeds tickets or run sd commands.
---

<!-- Generated by sd onboard (v0.1.1). Re-run it to update; local edits are overwritten. -->

# Seeds

Tickets live in \`.seeds/\` on **main**, so everyone sees the current state. Every change goes straight to main through \`seeds-publish\`, the one thing allowed to push to main. It pushes only \`.seeds/\`. Never commit \`.seeds/\` on a branch (the check fails a ticket branch that does) and don't run \`sd sync\`. Why: the harness's ADR-0001, "Seeds changes go to main directly". \`sd prime\` runs at session start and shows current work from your local copy, which may be behind main.

\`P\` below is short for \`node .claude/scripts/seeds-publish.mjs\`.

## Find work

\`\`\`bash
P --read -- sd ready          # unblocked, plan submitted if required
P --read -- sd list           # all open tickets
P --read -- sd show <id>      # full ticket, including its module scope
\`\`\`

\`--read\` runs the command on fresh main and changes nothing.

## Create tickets

\`\`\`bash
P -- sd create --type epic --title "Feature name"
P -- sd create --type task --title "..." --parent <epic> \\
  --module <name> --entry <path> --must-not-touch <a,b>
P -- sd dep add <ticket> <blocker>
\`\`\`

Each call is one commit on main and prints the real ticket id. Add \`-m "<message>"\` before \`--\` to set the commit message.

The module scope is set **only when the ticket is created**: which module the work belongs to, its entry point, and what it must not touch. The module flags are optional. Leave them off when the scope isn't clear yet, and never make up a scope.

Epic plans can give a step a \`"module"\`, and the task spawned from that step inherits it.

## Work a ticket

\`\`\`bash
P -- sd update <id> --status in_progress
P --read -- sd plan prompt <id>              # plan template, if the ticket requires one
P -- sd plan submit <id> --plan <abs-path>   # the command runs in a private checkout, so use an absolute path
P -- sd close <id> --reason "..."            # tickets with no PR only; a merged ticket PR is closed by the close-ticket Action
\`\`\`

Stay inside the ticket's module. If the work needs to touch something on its \`must not touch\` list, stop and ask.
`;

export function registerOnboardCommand(program: Command): void {
	program
		.command("onboard")
		.description("Add the Seeds skill and SessionStart hook for Claude Code")
		.action(() => {
			assertInitialized();
			const cwd = process.cwd();

			// 1. Skill file — loaded by the agent on demand, not every session
			const skillDir = join(cwd, ".claude", "skills", "seeds");
			const skillPath = join(skillDir, "SKILL.md");
			if (existsSync(skillPath) && readFileSync(skillPath, "utf-8") === SEEDS_SKILL) {
				console.log(chalk.dim("  Seeds skill already up to date"));
			} else {
				mkdirSync(skillDir, { recursive: true });
				writeFileSync(skillPath, SEEDS_SKILL, "utf-8");
				console.log(chalk.green("✓ Seeds skill written to .claude/skills/seeds/SKILL.md"));
			}

			// 2. SessionStart hook in .claude/settings.json
			const settingsPath = join(cwd, ".claude", "settings.json");
			const settings = existsSync(settingsPath)
				? (JSON.parse(readFileSync(settingsPath, "utf-8")) as Record<string, unknown>)
				: {};
			const hooks = (settings.hooks ?? {}) as Record<string, unknown>;
			const sessionStart = (hooks.SessionStart ?? []) as Array<{
				matcher: string;
				hooks: Array<{ type: string; command: string }>;
			}>;
			const present = sessionStart.some((entry) =>
				entry.hooks?.some((h) => h.command?.includes("sd prime")),
			);
			if (present) {
				console.log(chalk.dim("  SessionStart hook already present"));
			} else {
				sessionStart.push({ matcher: "", hooks: [{ type: "command", command: PRIME_COMMAND }] });
				hooks.SessionStart = sessionStart;
				settings.hooks = hooks;
				writeFileSync(settingsPath, `${JSON.stringify(settings, null, "\t")}\n`, "utf-8");
				console.log(chalk.green("✓ SessionStart hook added to .claude/settings.json"));
			}

			// 3. Remove the block older versions put in CLAUDE.md
			const claudeMdPath = join(cwd, "CLAUDE.md");
			if (existsSync(claudeMdPath)) {
				const content = readFileSync(claudeMdPath, "utf-8");
				if (LEGACY_BLOCK.test(content)) {
					const cleaned = content.replace(LEGACY_BLOCK, "\n\n").trim();
					writeFileSync(claudeMdPath, cleaned ? `${cleaned}\n` : "", "utf-8");
					console.log(chalk.green("✓ Removed old Seeds block from CLAUDE.md"));
				}
			}
		});
}
